### ISSUE TITLE
[Nuxt/Vite] paths in types are absolute. Incompatible with WSL2 and WebStorm

### ISSUE THREAD

**Issue by misaon** [unjs/nitro#1560]
### Environment

Nitro 2.5.2
Node 18.17

### Reproduction

https://github.com/nuxt/nuxt/issues/21827#issuecomment-1673358067

### Describe the bug

Why is the .nuxt folder and its dt.ts so inconsistent? Some places are relative imports, some places are absolute. WebStorm can't handle absolute paths in WSL2, so Nuxt 3 is unusable in that environment. It would make much more sense to me if all imports were relative.

**Comment by misaon** [comment]
https://github.com/unjs/nitro/blob/8c0473ca28a3ce170d5cf2cbfd0634889fb6881b/src/build.ts#L164C15-L164C15

**Comment by danielroe** [comment]
I believe this is already resolved on the edge. Would you check?

**Comment by misaon** [comment]
@danielroe Do you think it would be good to have support for controlling `tsconfig.server.json` in hook `prepare:types`? Similar to `tsconfig.json` for Nuxt. Currently it can only be controlled via the typescript propert in: `defineNuxtConfig > nitro > typescript > tsConfig`.

https://github.com/nuxt/nuxt/blob/20efac7d57fd66283140a224d653d92b6e41676a/packages/nuxt/src/core/nitro.ts#L355C13-L355C23

**Comment by misaon** [comment]
@danielroe @pi0  I just tested and unfortunately it still doesn't work properly... 😞 

`Nuxt 3.7.0-28201370.c8cba7a0 with Nitro 2.6.0-28201391.6af6fd1`

`.nuxt/tsconfig.server.json`: **OK**
`.nuxt/types/nitro-imports.d.ts`: **BAD**

```ts
// ...
export { defineCachedFunction, defineCachedEventHandler, cachedFunction, cachedEventHandler, useRuntimeConfig, useStorage, useNitroApp, defineNitroPlugin, nitroPlugin, defineRenderHandler, getRouteRules, useAppConfig, useEvent } from '/home/xxx/Projects/upscore/node_modules/.pnpm/nitropack-edge@2.6.0-28201391.6af6fd1/node_modules/nitropack-edge/dist/runtime';
// ...
```

**Comment by danielroe** [comment]
@misaon Would you provide a reproduction?

**Comment by misaon** [comment]
> @misaon Would you provide a reproduction?

https://github.com/nuxt/nuxt/issues/21827#issuecomment-1678594399

**Comment by misaon** [comment]
@danielroe tested, works great.
