### ISSUE TITLE
externalized packages aren't traced properly

### ISSUE THREAD

**Issue by mahdiboomeri** [unjs/nitro#722]
### Environment

- Operating System: Linux
- Node Version: v18.7.0
- Nitro: latest

### Reproduction

https://github.com/mahdiboomeri/nitro-externalized-issue

my older reproduction for context:
https://github.com/mahdiboomeri/nuxt3-externalized-issue

### Describe the bug

related to https://github.com/nuxt/framework/issues/7105 and #515 

When using packages with the same dependency but conflicting versions, the externalized dependency files aren't traced properly. (sorry if it's a bit unclear this was the best way i could explain it)
for example in the reproduction repo i'm using `sharp` and `jsonwebtoken` which both rely on different versions of `semver`.

I get the following file structure in `.output/server/node_modules/semver`
```
- 📂 semver
   - 📂 classes
     - 📄 semver.js
   - 📂 functions
     - 📄 coerce.js
     - 📄 compare.js
     - 📄 gte.js
     - 📄 parse.js
   - 📂 internal
     - 📄 constants.js
     - 📄 debug.js
     - 📄 identifiers.js
     - 📄 parse\-options.js
     - 📄 re.js
   - 📄 package.json

```

What it should be
```
- 📂 semver
   - 📂 classes
     - 📄 comparator.js
     - 📄 range.js
     - 📄 semver.js
   - 📂 functions
     - 📄 clean.js
     - 📄 cmp.js
     - 📄 coerce.js
     - 📄 compare\-build.js
     - 📄 compare\-loose.js
     - 📄 compare.js
     - 📄 diff.js
     - 📄 eq.js
     - 📄 gt.js
     - 📄 gte.js
     - 📄 inc.js
     - 📄 lt.js
     - 📄 lte.js
     - 📄 major.js
     - 📄 minor.js
     - 📄 neq.js
     - 📄 parse.js
     - 📄 patch.js
     - 📄 prerelease.js
     - 📄 rcompare.js
     - 📄 rsort.js
     - 📄 satisfies.js
     - 📄 sort.js
     - 📄 valid.js
   - 📂 internal
     - 📄 constants.js
     - 📄 debug.js
     - 📄 identifiers.js
     - 📄 parse\-options.js
     - 📄 re.js
   - 📂 ranges
     - 📄 gtr.js
     - 📄 intersects.js
     - 📄 ltr.js
     - 📄 max\-satisfying.js
     - 📄 min\-satisfying.js
     - 📄 min\-version.js
     - 📄 outside.js
     - 📄 simplify.js
     - 📄 subset.js
     - 📄 to\-comparators.js
     - 📄 valid.js
   - 📄 index.js
   - 📄 package.json
   - 📄 preload.js  
```

I understand the issue isn't related to these specific packages, you can find more examples in the https://github.com/nuxt/framework/issues/7105 comments
### Additional context

This was partially fixed in #515 but the problem is still there

**Comment by itpropro** [comment]
Probably a duplicate of #612 ?

**Comment by manniL** [comment]
Thinking so too! Let's track in #612

**Comment by mahdiboomeri** [comment]
I did some investigation and I think I understand why this happens.

The root of the problem is the [externals](https://github.com/unjs/nitro/blob/main/src/rollup/plugins/externals.ts) plugin. It checks for externalized packages and passes them through `@vercel/nft` to trace only the needed files. That's why the output files are smaller than the input (as I demonstrated in the issue description). 
So far, nothing that'd break the app since `@vercel/nft` does its job without any issue. The problem only begins when nitro tries to use only the latest version of the dependency and ignores any files regarding the older one. This is fine where the version difference is patch or minor but for major version differences, this will break the bundle in most cases. 

For the example I showed in the reproduction: 
`jsonwebtoken` relies on `semver@5.7.1` and `sharp` relies on `semver@7.3.8`. in the bundling process, nitro chooses the latest version (7.3.8) and passes that through `@vercel/nft` to get the traced files, So the files are only traced for `sharp` package. since the code structure is completely different between `semver@5.7.1` and `semver@7.3.8`, `jsonwebtoken` can't import the files it needs, and hence the production breaks. 

One nice thing is that nitro gives a warning when doing this:

```bash
 WARN  Multiple major versions of package semver are being externalized. Picking latest version: 

  - /semver@5.7.1/node_modules/semver@5.7.1
  + /semver@7.3.8/node_modules/semver@7.3.8
```
Since this problem isn't related to any specific dependency, IMO we should keep both versions in the bundle by default (if the version difference is major at least). Also, we should provide an option in `nitro.config` so custom deps can be specified to be excluded from optimizing (because some deps may not follow semantic versioning and have breaking changes in a minor release)

**About #612**:
I don't think that these issues are the same for the following reasons:
- The problem I mentioned shouldn't happen in development mode since it's related to rollup bundling process.
- You most likely get the warning I mentioned earlier when building for production (which isn't the case for #612's reproduction)

@manniL  Maybe we can consider re-opening this?

**Comment by itpropro** [comment]
> 

Hi @mahdiboomeri,
I think it’s actually the same issue. The behavior you describes is exactly the same I experienced with e.g. the @azure/identity package. It happens after the build and Nitro throws multiple warning about different versions and that it is picking the newest one.
#612 should also be fixed, if all packages are considered for the bundle if they are referenced by a package or a dependency.

**Comment by mahdiboomeri** [comment]
hi @itpropro
Thanks for the further explanation, Based on what you described I think you're right.
I didn't have much context on #612 other than the reproduction that's why they sounded different to me
i mananged to find some success in fixing the issue with just hacking around, i'm working on a better fix, if it works I probably make a PR

**Comment by mahdiboomeri** [comment]
fixed in #782

**Comment by itpropro** [comment]
I cannot confirm this as fixed unfortunately. I still get the same errors with external deps after building. None of them occur with `nitro dev`, but with `nitro build` and running it, I still get errors like:

```
coreTracing.createSpanFunction is not a function
```

With the trace being 

```
[nitro] [request error] [unhandled] coreTracing.createSpanFunction is not a function
  at Object.<anonymous> (E:\repos\project\.output\server\node_modules\@azure\app-configuration\dist\index.js:2053:32)
  at Module._compile (node:internal/modules/cjs/loader:1159:14)
  at Module._extensions..js (node:internal/modules/cjs/loader:1213:10)
  at Module.load (node:internal/modules/cjs/loader:1037:32)
  at Module._load (node:internal/modules/cjs/loader:878:12)
  at ModuleWrap.<anonymous> (node:internal/modules/esm/translators:169:29)
  at ModuleJob.run (node:internal/modules/esm/module_job:193:25)
  at async Promise.all (index 0)
  at async ESMLoader.import (node:internal/modules/esm/loader:530:24)
  at async Object.handler (/E:/repos/project/.output/server/chunks/node-server.mjs:455:19)
[nitro] [dev] [unhandledRejection] TypeError: coreTracing.createSpanFunction is not a function
```
